'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
'
Namespace DXService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DXSampleWebServiceSoap", [Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class DXSampleWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetDataViewOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Settings.Default.DXServiceHelper_DXService_DXSampleWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetDataViewCompleted As GetDataViewCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devexpress.com/GetDataView", RequestNamespace:="http://www.devexpress.com/", ResponseNamespace:="http://www.devexpress.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDataView(ByVal className As String, ByVal properties() As ViewProperty, ByVal filter As String) As String
            Dim results() As Object = Me.Invoke("GetDataView", New Object() {className, properties, filter})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDataViewAsync(ByVal className As String, ByVal properties() As ViewProperty, ByVal filter As String)
            Me.GetDataViewAsync(className, properties, filter, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDataViewAsync(ByVal className As String, ByVal properties() As ViewProperty, ByVal filter As String, ByVal userState As Object)
            If (Me.GetDataViewOperationCompleted Is Nothing) Then
                Me.GetDataViewOperationCompleted = AddressOf Me.OnGetDataViewOperationCompleted
            End If
            Me.InvokeAsync("GetDataView", New Object() {className, properties, filter}, Me.GetDataViewOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDataViewOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDataViewCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDataViewCompleted(Me, New GetDataViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class ViewProperty
        
        Private nameField As String
        
        Private sortingField As SortDirection
        
        Private propertyField As CriteriaOperator
        
        Private groupField As Boolean
        
        Private fetchField As Boolean
        
        Public Sub New()
            MyBase.New
            Me.sortingField = SortDirection.None
            Me.groupField = false
            Me.fetchField = true
        End Sub
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.ComponentModel.DefaultValueAttribute(SortDirection.None)>  _
        Public Property Sorting() As SortDirection
            Get
                Return Me.sortingField
            End Get
            Set
                Me.sortingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [Property]() As CriteriaOperator
            Get
                Return Me.propertyField
            End Get
            Set
                Me.propertyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.ComponentModel.DefaultValueAttribute(false)>  _
        Public Property Group() As Boolean
            Get
                Return Me.groupField
            End Get
            Set
                Me.groupField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.ComponentModel.DefaultValueAttribute(true)>  _
        Public Property Fetch() As Boolean
            Get
                Return Me.fetchField
            End Get
            Set
                Me.fetchField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Public Enum SortDirection
        
        '''<remarks/>
        None
        
        '''<remarks/>
        Ascending
        
        '''<remarks/>
        Descending
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(OperandValue)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ParameterValue)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GroupOperator)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(QueryOperand)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BinaryOperator)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(InOperator)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(FunctionOperator)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(UnaryOperator)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(NotOperator)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(NullOperator)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AggregateOperand)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ContainsOperator)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(OperandProperty)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BetweenOperator)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(QuerySubQueryContainer)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public MustInherit Class CriteriaOperator
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class TimeSpan
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class DBNull
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(BaseStatement)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class JoinNode
        
        Private subNodesField() As JoinNode
        
        Private conditionField As CriteriaOperator
        
        Private aliasField As String
        
        Private typeField As JoinType
        
        Private tableNameField As String
        
        Public Sub New()
            MyBase.New
            Me.typeField = JoinType.Inner
        End Sub
        
        '''<remarks/>
        Public Property SubNodes() As JoinNode()
            Get
                Return Me.subNodesField
            End Get
            Set
                Me.subNodesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Condition() As CriteriaOperator
            Get
                Return Me.conditionField
            End Get
            Set
                Me.conditionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property [Alias]() As String
            Get
                Return Me.aliasField
            End Get
            Set
                Me.aliasField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(JoinType.Inner)>  _
        Public Property Type() As JoinType
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TableName() As String
            Get
                Return Me.tableNameField
            End Get
            Set
                Me.tableNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Public Enum JoinType
        
        '''<remarks/>
        Inner
        
        '''<remarks/>
        LeftOuter
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public MustInherit Class BaseStatement
        Inherits JoinNode
        
        Private operandsField() As CriteriaOperator
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(GetType(AggregateOperand)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(BetweenOperator)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(BinaryOperator)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(ContainsOperator)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(FunctionOperator)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(GroupOperator)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(InOperator)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(NotOperator)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(NullOperator)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(OperandProperty)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(OperandValue)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(QueryOperand)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(QuerySubQueryContainer)),  _
         System.Xml.Serialization.XmlArrayItemAttribute(GetType(UnaryOperator))>  _
        Public Property Operands() As CriteriaOperator()
            Get
                Return Me.operandsField
            End Get
            Set
                Me.operandsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ContainsOperator)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class AggregateOperand
        Inherits CriteriaOperator
        
        Private conditionField As CriteriaOperator
        
        Private collectionPropertyField As OperandProperty
        
        Private aggregatedExpressionField As CriteriaOperator
        
        Private aggregateTypeField As Aggregate
        
        '''<remarks/>
        Public Property Condition() As CriteriaOperator
            Get
                Return Me.conditionField
            End Get
            Set
                Me.conditionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CollectionProperty() As OperandProperty
            Get
                Return Me.collectionPropertyField
            End Get
            Set
                Me.collectionPropertyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AggregatedExpression() As CriteriaOperator
            Get
                Return Me.aggregatedExpressionField
            End Get
            Set
                Me.aggregatedExpressionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AggregateType() As Aggregate
            Get
                Return Me.aggregateTypeField
            End Get
            Set
                Me.aggregateTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class OperandProperty
        Inherits CriteriaOperator
        
        Private propertyNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property PropertyName() As String
            Get
                Return Me.propertyNameField
            End Get
            Set
                Me.propertyNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Public Enum Aggregate
        
        '''<remarks/>
        Exists
        
        '''<remarks/>
        Count
        
        '''<remarks/>
        Max
        
        '''<remarks/>
        Min
        
        '''<remarks/>
        Avg
        
        '''<remarks/>
        Sum
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class ContainsOperator
        Inherits AggregateOperand
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class BetweenOperator
        Inherits CriteriaOperator
        
        Private beginExpressionField As CriteriaOperator
        
        Private endExpressionField As CriteriaOperator
        
        Private testExpressionField As CriteriaOperator
        
        '''<remarks/>
        Public Property BeginExpression() As CriteriaOperator
            Get
                Return Me.beginExpressionField
            End Get
            Set
                Me.beginExpressionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EndExpression() As CriteriaOperator
            Get
                Return Me.endExpressionField
            End Get
            Set
                Me.endExpressionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TestExpression() As CriteriaOperator
            Get
                Return Me.testExpressionField
            End Get
            Set
                Me.testExpressionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class BinaryOperator
        Inherits CriteriaOperator
        
        Private leftOperandField As CriteriaOperator
        
        Private rightOperandField As CriteriaOperator
        
        Private operatorTypeField As BinaryOperatorType
        
        '''<remarks/>
        Public Property LeftOperand() As CriteriaOperator
            Get
                Return Me.leftOperandField
            End Get
            Set
                Me.leftOperandField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RightOperand() As CriteriaOperator
            Get
                Return Me.rightOperandField
            End Get
            Set
                Me.rightOperandField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property OperatorType() As BinaryOperatorType
            Get
                Return Me.operatorTypeField
            End Get
            Set
                Me.operatorTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Public Enum BinaryOperatorType
        
        '''<remarks/>
        Equal
        
        '''<remarks/>
        NotEqual
        
        '''<remarks/>
        Greater
        
        '''<remarks/>
        Less
        
        '''<remarks/>
        LessOrEqual
        
        '''<remarks/>
        GreaterOrEqual
        
        '''<remarks/>
        [Like]
        
        '''<remarks/>
        BitwiseAnd
        
        '''<remarks/>
        BitwiseOr
        
        '''<remarks/>
        BitwiseXor
        
        '''<remarks/>
        Divide
        
        '''<remarks/>
        Modulo
        
        '''<remarks/>
        Multiply
        
        '''<remarks/>
        Plus
        
        '''<remarks/>
        Minus
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class FunctionOperator
        Inherits CriteriaOperator
        
        Private operandsField() As CriteriaOperator
        
        Private operatorTypeField As FunctionOperatorType
        
        '''<remarks/>
        Public Property Operands() As CriteriaOperator()
            Get
                Return Me.operandsField
            End Get
            Set
                Me.operandsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property OperatorType() As FunctionOperatorType
            Get
                Return Me.operatorTypeField
            End Get
            Set
                Me.operatorTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Public Enum FunctionOperatorType
        
        '''<remarks/>
        None
        
        '''<remarks/>
        Trim
        
        '''<remarks/>
        Len
        
        '''<remarks/>
        Substring
        
        '''<remarks/>
        Iif
        
        '''<remarks/>
        IsNull
        
        '''<remarks/>
        Upper
        
        '''<remarks/>
        Lower
        
        '''<remarks/>
        Custom
        
        '''<remarks/>
        Concat
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class GroupOperator
        Inherits CriteriaOperator
        
        Private operandsField() As CriteriaOperator
        
        Private operatorTypeField As GroupOperatorType
        
        '''<remarks/>
        Public Property Operands() As CriteriaOperator()
            Get
                Return Me.operandsField
            End Get
            Set
                Me.operandsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property OperatorType() As GroupOperatorType
            Get
                Return Me.operatorTypeField
            End Get
            Set
                Me.operatorTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Public Enum GroupOperatorType
        
        '''<remarks/>
        [And]
        
        '''<remarks/>
        [Or]
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class InOperator
        Inherits CriteriaOperator
        
        Private leftOperandField As CriteriaOperator
        
        Private operandsField() As CriteriaOperator
        
        '''<remarks/>
        Public Property LeftOperand() As CriteriaOperator
            Get
                Return Me.leftOperandField
            End Get
            Set
                Me.leftOperandField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Operands() As CriteriaOperator()
            Get
                Return Me.operandsField
            End Get
            Set
                Me.operandsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class NotOperator
        Inherits UnaryOperator
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(NotOperator)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(NullOperator)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class UnaryOperator
        Inherits CriteriaOperator
        
        Private operandField As CriteriaOperator
        
        Private operatorTypeField As UnaryOperatorType
        
        '''<remarks/>
        Public Property Operand() As CriteriaOperator
            Get
                Return Me.operandField
            End Get
            Set
                Me.operandField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property OperatorType() As UnaryOperatorType
            Get
                Return Me.operatorTypeField
            End Get
            Set
                Me.operatorTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Public Enum UnaryOperatorType
        
        '''<remarks/>
        BitwiseNot
        
        '''<remarks/>
        Plus
        
        '''<remarks/>
        Minus
        
        '''<remarks/>
        [Not]
        
        '''<remarks/>
        IsNull
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class NullOperator
        Inherits UnaryOperator
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ParameterValue)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class OperandValue
        Inherits CriteriaOperator
        
        Private itemField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DBNull", GetType(DBNull)),  _
         System.Xml.Serialization.XmlElementAttribute("TimeSpan", GetType(TimeSpan)),  _
         System.Xml.Serialization.XmlElementAttribute("base64Binary", GetType(Byte()), DataType:="base64Binary"),  _
         System.Xml.Serialization.XmlElementAttribute("boolean", GetType(Boolean)),  _
         System.Xml.Serialization.XmlElementAttribute("byte", GetType(SByte)),  _
         System.Xml.Serialization.XmlElementAttribute("char", GetType(Char)),  _
         System.Xml.Serialization.XmlElementAttribute("dateTime", GetType(Date)),  _
         System.Xml.Serialization.XmlElementAttribute("decimal", GetType(Decimal)),  _
         System.Xml.Serialization.XmlElementAttribute("double", GetType(Double)),  _
         System.Xml.Serialization.XmlElementAttribute("float", GetType(Single)),  _
         System.Xml.Serialization.XmlElementAttribute("guid", GetType(System.Guid)),  _
         System.Xml.Serialization.XmlElementAttribute("int", GetType(Integer)),  _
         System.Xml.Serialization.XmlElementAttribute("long", GetType(Long)),  _
         System.Xml.Serialization.XmlElementAttribute("short", GetType(Short)),  _
         System.Xml.Serialization.XmlElementAttribute("string", GetType(String)),  _
         System.Xml.Serialization.XmlElementAttribute("unsignedByte", GetType(Byte)),  _
         System.Xml.Serialization.XmlElementAttribute("unsignedInt", GetType(UInteger)),  _
         System.Xml.Serialization.XmlElementAttribute("unsignedLong", GetType(ULong)),  _
         System.Xml.Serialization.XmlElementAttribute("unsignedShort", GetType(UShort))>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class ParameterValue
        Inherits OperandValue
        
        Private tagField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Tag() As Integer
            Get
                Return Me.tagField
            End Get
            Set
                Me.tagField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class QueryOperand
        Inherits CriteriaOperator
        
        Private columnNameField As String
        
        Private columnTypeField As DBColumnType
        
        Private nodeAliasField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ColumnName() As String
            Get
                Return Me.columnNameField
            End Get
            Set
                Me.columnNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ColumnType() As DBColumnType
            Get
                Return Me.columnTypeField
            End Get
            Set
                Me.columnTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NodeAlias() As String
            Get
                Return Me.nodeAliasField
            End Get
            Set
                Me.nodeAliasField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Public Enum DBColumnType
        
        '''<remarks/>
        Unknown
        
        '''<remarks/>
        [Boolean]
        
        '''<remarks/>
        [Byte]
        
        '''<remarks/>
        [SByte]
        
        '''<remarks/>
        [Char]
        
        '''<remarks/>
        [Decimal]
        
        '''<remarks/>
        [Double]
        
        '''<remarks/>
        [Single]
        
        '''<remarks/>
        Int32
        
        '''<remarks/>
        UInt32
        
        '''<remarks/>
        Int16
        
        '''<remarks/>
        UInt16
        
        '''<remarks/>
        Int64
        
        '''<remarks/>
        UInt64
        
        '''<remarks/>
        [String]
        
        '''<remarks/>
        DateTime
        
        '''<remarks/>
        Guid
        
        '''<remarks/>
        TimeSpan
        
        '''<remarks/>
        ByteArray
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.devexpress.com/")>  _
    Partial Public Class QuerySubQueryContainer
        Inherits CriteriaOperator
        
        Private nodeField As BaseStatement
        
        Private aggregatePropertyField As CriteriaOperator
        
        Private aggregateTypeField As Aggregate
        
        '''<remarks/>
        Public Property Node() As BaseStatement
            Get
                Return Me.nodeField
            End Get
            Set
                Me.nodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AggregateProperty() As CriteriaOperator
            Get
                Return Me.aggregatePropertyField
            End Get
            Set
                Me.aggregatePropertyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property AggregateType() As Aggregate
            Get
                Return Me.aggregateTypeField
            End Get
            Set
                Me.aggregateTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub GetDataViewCompletedEventHandler(ByVal sender As Object, ByVal e As GetDataViewCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDataViewCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
