//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30128.1.
// 
#pragma warning disable 1591

namespace DXServiceHelper.DXService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30128.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DXSampleWebServiceSoap", Namespace="http://www.devexpress.com/")]
    public partial class DXSampleWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataViewOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DXSampleWebService() {
            this.Url = global::DXServiceHelper.Properties.Settings.Default.DXServiceHelper_DXService_DXSampleWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataViewCompletedEventHandler GetDataViewCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devexpress.com/GetDataView", RequestNamespace="http://www.devexpress.com/", ResponseNamespace="http://www.devexpress.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDataView(string className, ViewProperty[] properties, string filter) {
            object[] results = this.Invoke("GetDataView", new object[] {
                        className,
                        properties,
                        filter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataViewAsync(string className, ViewProperty[] properties, string filter) {
            this.GetDataViewAsync(className, properties, filter, null);
        }
        
        /// <remarks/>
        public void GetDataViewAsync(string className, ViewProperty[] properties, string filter, object userState) {
            if ((this.GetDataViewOperationCompleted == null)) {
                this.GetDataViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataViewOperationCompleted);
            }
            this.InvokeAsync("GetDataView", new object[] {
                        className,
                        properties,
                        filter}, this.GetDataViewOperationCompleted, userState);
        }
        
        private void OnGetDataViewOperationCompleted(object arg) {
            if ((this.GetDataViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataViewCompleted(this, new GetDataViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class ViewProperty {
        
        private string nameField;
        
        private SortDirection sortingField;
        
        private CriteriaOperator propertyField;
        
        private bool groupField;
        
        private bool fetchField;
        
        public ViewProperty() {
            this.sortingField = SortDirection.None;
            this.groupField = false;
            this.fetchField = true;
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(SortDirection.None)]
        public SortDirection Sorting {
            get {
                return this.sortingField;
            }
            set {
                this.sortingField = value;
            }
        }
        
        /// <remarks/>
        public CriteriaOperator Property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Fetch {
            get {
                return this.fetchField;
            }
            set {
                this.fetchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public enum SortDirection {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Ascending,
        
        /// <remarks/>
        Descending,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AggregateOperand))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContainsOperator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BetweenOperator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperandProperty))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QuerySubQueryContainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnaryOperator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NotOperator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NullOperator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinaryOperator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InOperator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupOperator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperandValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JoinOperand))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FunctionOperator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QueryOperand))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public abstract partial class CriteriaOperator {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseStatement))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class JoinNode {
        
        private JoinNode[] subNodesField;
        
        private CriteriaOperator conditionField;
        
        private string aliasField;
        
        private JoinType typeField;
        
        private string tableNameField;
        
        public JoinNode() {
            this.typeField = JoinType.Inner;
        }
        
        /// <remarks/>
        public JoinNode[] SubNodes {
            get {
                return this.subNodesField;
            }
            set {
                this.subNodesField = value;
            }
        }
        
        /// <remarks/>
        public CriteriaOperator Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(JoinType.Inner)]
        public JoinType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public enum JoinType {
        
        /// <remarks/>
        Inner,
        
        /// <remarks/>
        LeftOuter,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public abstract partial class BaseStatement : JoinNode {
        
        private CriteriaOperator[] operandsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(AggregateOperand))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(BetweenOperator))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(BinaryOperator))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(ContainsOperator))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(FunctionOperator))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(GroupOperator))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(InOperator))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(JoinOperand))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(NotOperator))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(NullOperator))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(OperandProperty))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(OperandValue))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(QueryOperand))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(QuerySubQueryContainer))]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(UnaryOperator))]
        public CriteriaOperator[] Operands {
            get {
                return this.operandsField;
            }
            set {
                this.operandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContainsOperator))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class AggregateOperand : CriteriaOperator {
        
        private CriteriaOperator conditionField;
        
        private OperandProperty collectionPropertyField;
        
        private CriteriaOperator aggregatedExpressionField;
        
        private Aggregate aggregateTypeField;
        
        /// <remarks/>
        public CriteriaOperator Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public OperandProperty CollectionProperty {
            get {
                return this.collectionPropertyField;
            }
            set {
                this.collectionPropertyField = value;
            }
        }
        
        /// <remarks/>
        public CriteriaOperator AggregatedExpression {
            get {
                return this.aggregatedExpressionField;
            }
            set {
                this.aggregatedExpressionField = value;
            }
        }
        
        /// <remarks/>
        public Aggregate AggregateType {
            get {
                return this.aggregateTypeField;
            }
            set {
                this.aggregateTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class OperandProperty : CriteriaOperator {
        
        private string propertyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PropertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public enum Aggregate {
        
        /// <remarks/>
        Exists,
        
        /// <remarks/>
        Count,
        
        /// <remarks/>
        Max,
        
        /// <remarks/>
        Min,
        
        /// <remarks/>
        Avg,
        
        /// <remarks/>
        Sum,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class ContainsOperator : AggregateOperand {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class BetweenOperator : CriteriaOperator {
        
        private CriteriaOperator beginExpressionField;
        
        private CriteriaOperator endExpressionField;
        
        private CriteriaOperator testExpressionField;
        
        /// <remarks/>
        public CriteriaOperator BeginExpression {
            get {
                return this.beginExpressionField;
            }
            set {
                this.beginExpressionField = value;
            }
        }
        
        /// <remarks/>
        public CriteriaOperator EndExpression {
            get {
                return this.endExpressionField;
            }
            set {
                this.endExpressionField = value;
            }
        }
        
        /// <remarks/>
        public CriteriaOperator TestExpression {
            get {
                return this.testExpressionField;
            }
            set {
                this.testExpressionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class BinaryOperator : CriteriaOperator {
        
        private CriteriaOperator leftOperandField;
        
        private CriteriaOperator rightOperandField;
        
        private BinaryOperatorType operatorTypeField;
        
        /// <remarks/>
        public CriteriaOperator LeftOperand {
            get {
                return this.leftOperandField;
            }
            set {
                this.leftOperandField = value;
            }
        }
        
        /// <remarks/>
        public CriteriaOperator RightOperand {
            get {
                return this.rightOperandField;
            }
            set {
                this.rightOperandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BinaryOperatorType OperatorType {
            get {
                return this.operatorTypeField;
            }
            set {
                this.operatorTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public enum BinaryOperatorType {
        
        /// <remarks/>
        Equal,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Like,
        
        /// <remarks/>
        BitwiseAnd,
        
        /// <remarks/>
        BitwiseOr,
        
        /// <remarks/>
        BitwiseXor,
        
        /// <remarks/>
        Divide,
        
        /// <remarks/>
        Modulo,
        
        /// <remarks/>
        Multiply,
        
        /// <remarks/>
        Plus,
        
        /// <remarks/>
        Minus,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class FunctionOperator : CriteriaOperator {
        
        private CriteriaOperator[] operandsField;
        
        private FunctionOperatorType operatorTypeField;
        
        /// <remarks/>
        public CriteriaOperator[] Operands {
            get {
                return this.operandsField;
            }
            set {
                this.operandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FunctionOperatorType OperatorType {
            get {
                return this.operatorTypeField;
            }
            set {
                this.operatorTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public enum FunctionOperatorType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Custom,
        
        /// <remarks/>
        Iif,
        
        /// <remarks/>
        IsNull,
        
        /// <remarks/>
        IsNullOrEmpty,
        
        /// <remarks/>
        Trim,
        
        /// <remarks/>
        Len,
        
        /// <remarks/>
        Substring,
        
        /// <remarks/>
        Upper,
        
        /// <remarks/>
        Lower,
        
        /// <remarks/>
        Concat,
        
        /// <remarks/>
        Ascii,
        
        /// <remarks/>
        Char,
        
        /// <remarks/>
        ToStr,
        
        /// <remarks/>
        Replace,
        
        /// <remarks/>
        Reverse,
        
        /// <remarks/>
        Insert,
        
        /// <remarks/>
        CharIndex,
        
        /// <remarks/>
        Remove,
        
        /// <remarks/>
        Abs,
        
        /// <remarks/>
        Sqr,
        
        /// <remarks/>
        Cos,
        
        /// <remarks/>
        Sin,
        
        /// <remarks/>
        Atn,
        
        /// <remarks/>
        Exp,
        
        /// <remarks/>
        Log,
        
        /// <remarks/>
        Rnd,
        
        /// <remarks/>
        Tan,
        
        /// <remarks/>
        Power,
        
        /// <remarks/>
        Sign,
        
        /// <remarks/>
        Round,
        
        /// <remarks/>
        Ceiling,
        
        /// <remarks/>
        Floor,
        
        /// <remarks/>
        Acos,
        
        /// <remarks/>
        Asin,
        
        /// <remarks/>
        Atn2,
        
        /// <remarks/>
        BigMul,
        
        /// <remarks/>
        Cosh,
        
        /// <remarks/>
        Log10,
        
        /// <remarks/>
        Sinh,
        
        /// <remarks/>
        Tanh,
        
        /// <remarks/>
        PadLeft,
        
        /// <remarks/>
        PadRight,
        
        /// <remarks/>
        LocalDateTimeThisYear,
        
        /// <remarks/>
        LocalDateTimeThisMonth,
        
        /// <remarks/>
        LocalDateTimeLastWeek,
        
        /// <remarks/>
        LocalDateTimeThisWeek,
        
        /// <remarks/>
        LocalDateTimeYesterday,
        
        /// <remarks/>
        LocalDateTimeToday,
        
        /// <remarks/>
        LocalDateTimeNow,
        
        /// <remarks/>
        LocalDateTimeTomorrow,
        
        /// <remarks/>
        LocalDateTimeDayAfterTomorrow,
        
        /// <remarks/>
        LocalDateTimeNextWeek,
        
        /// <remarks/>
        LocalDateTimeTwoWeeksAway,
        
        /// <remarks/>
        LocalDateTimeNextMonth,
        
        /// <remarks/>
        LocalDateTimeNextYear,
        
        /// <remarks/>
        IsOutlookIntervalBeyondThisYear,
        
        /// <remarks/>
        IsOutlookIntervalLaterThisYear,
        
        /// <remarks/>
        IsOutlookIntervalLaterThisMonth,
        
        /// <remarks/>
        IsOutlookIntervalNextWeek,
        
        /// <remarks/>
        IsOutlookIntervalLaterThisWeek,
        
        /// <remarks/>
        IsOutlookIntervalTomorrow,
        
        /// <remarks/>
        IsOutlookIntervalToday,
        
        /// <remarks/>
        IsOutlookIntervalYesterday,
        
        /// <remarks/>
        IsOutlookIntervalEarlierThisWeek,
        
        /// <remarks/>
        IsOutlookIntervalLastWeek,
        
        /// <remarks/>
        IsOutlookIntervalEarlierThisMonth,
        
        /// <remarks/>
        IsOutlookIntervalEarlierThisYear,
        
        /// <remarks/>
        IsOutlookIntervalPriorThisYear,
        
        /// <remarks/>
        GetDate,
        
        /// <remarks/>
        GetMilliSecond,
        
        /// <remarks/>
        GetSecond,
        
        /// <remarks/>
        GetMinute,
        
        /// <remarks/>
        GetHour,
        
        /// <remarks/>
        GetDay,
        
        /// <remarks/>
        GetMonth,
        
        /// <remarks/>
        GetYear,
        
        /// <remarks/>
        GetDayOfWeek,
        
        /// <remarks/>
        GetDayOfYear,
        
        /// <remarks/>
        GetTimeOfDay,
        
        /// <remarks/>
        Now,
        
        /// <remarks/>
        UtcNow,
        
        /// <remarks/>
        Today,
        
        /// <remarks/>
        AddTimeSpan,
        
        /// <remarks/>
        AddTicks,
        
        /// <remarks/>
        AddMilliSeconds,
        
        /// <remarks/>
        AddSeconds,
        
        /// <remarks/>
        AddMinutes,
        
        /// <remarks/>
        AddHours,
        
        /// <remarks/>
        AddDays,
        
        /// <remarks/>
        AddMonths,
        
        /// <remarks/>
        AddYears,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class GroupOperator : CriteriaOperator {
        
        private CriteriaOperator[] operandsField;
        
        private GroupOperatorType operatorTypeField;
        
        /// <remarks/>
        public CriteriaOperator[] Operands {
            get {
                return this.operandsField;
            }
            set {
                this.operandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public GroupOperatorType OperatorType {
            get {
                return this.operatorTypeField;
            }
            set {
                this.operatorTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public enum GroupOperatorType {
        
        /// <remarks/>
        And,
        
        /// <remarks/>
        Or,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class InOperator : CriteriaOperator {
        
        private CriteriaOperator leftOperandField;
        
        private CriteriaOperator[] operandsField;
        
        /// <remarks/>
        public CriteriaOperator LeftOperand {
            get {
                return this.leftOperandField;
            }
            set {
                this.leftOperandField = value;
            }
        }
        
        /// <remarks/>
        public CriteriaOperator[] Operands {
            get {
                return this.operandsField;
            }
            set {
                this.operandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class JoinOperand : CriteriaOperator {
        
        private CriteriaOperator conditionField;
        
        private string joinTypeNameField;
        
        private CriteriaOperator aggregatedExpressionField;
        
        private Aggregate aggregateTypeField;
        
        /// <remarks/>
        public CriteriaOperator Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public string JoinTypeName {
            get {
                return this.joinTypeNameField;
            }
            set {
                this.joinTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public CriteriaOperator AggregatedExpression {
            get {
                return this.aggregatedExpressionField;
            }
            set {
                this.aggregatedExpressionField = value;
            }
        }
        
        /// <remarks/>
        public Aggregate AggregateType {
            get {
                return this.aggregateTypeField;
            }
            set {
                this.aggregateTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class NotOperator : UnaryOperator {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NotOperator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NullOperator))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class UnaryOperator : CriteriaOperator {
        
        private CriteriaOperator operandField;
        
        private UnaryOperatorType operatorTypeField;
        
        /// <remarks/>
        public CriteriaOperator Operand {
            get {
                return this.operandField;
            }
            set {
                this.operandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnaryOperatorType OperatorType {
            get {
                return this.operatorTypeField;
            }
            set {
                this.operatorTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public enum UnaryOperatorType {
        
        /// <remarks/>
        BitwiseNot,
        
        /// <remarks/>
        Plus,
        
        /// <remarks/>
        Minus,
        
        /// <remarks/>
        Not,
        
        /// <remarks/>
        IsNull,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class NullOperator : UnaryOperator {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class OperandValue : CriteriaOperator {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DBNull", typeof(DBNull))]
        [System.Xml.Serialization.XmlElementAttribute("TimeSpan", typeof(TimeSpan))]
        [System.Xml.Serialization.XmlElementAttribute("base64Binary", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("boolean", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("byte", typeof(sbyte))]
        [System.Xml.Serialization.XmlElementAttribute("char", typeof(char))]
        [System.Xml.Serialization.XmlElementAttribute("dateTime", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlElementAttribute("decimal", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("double", typeof(double))]
        [System.Xml.Serialization.XmlElementAttribute("float", typeof(float))]
        [System.Xml.Serialization.XmlElementAttribute("guid", typeof(System.Guid))]
        [System.Xml.Serialization.XmlElementAttribute("int", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("long", typeof(long))]
        [System.Xml.Serialization.XmlElementAttribute("short", typeof(short))]
        [System.Xml.Serialization.XmlElementAttribute("string", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("unsignedByte", typeof(byte))]
        [System.Xml.Serialization.XmlElementAttribute("unsignedInt", typeof(uint))]
        [System.Xml.Serialization.XmlElementAttribute("unsignedLong", typeof(ulong))]
        [System.Xml.Serialization.XmlElementAttribute("unsignedShort", typeof(ushort))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class DBNull {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class TimeSpan {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class ParameterValue : OperandValue {
        
        private int tagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class QueryOperand : CriteriaOperator {
        
        private string columnNameField;
        
        private DBColumnType columnTypeField;
        
        private string nodeAliasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DBColumnType ColumnType {
            get {
                return this.columnTypeField;
            }
            set {
                this.columnTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NodeAlias {
            get {
                return this.nodeAliasField;
            }
            set {
                this.nodeAliasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public enum DBColumnType {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        SByte,
        
        /// <remarks/>
        Char,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        Int32,
        
        /// <remarks/>
        UInt32,
        
        /// <remarks/>
        Int16,
        
        /// <remarks/>
        UInt16,
        
        /// <remarks/>
        Int64,
        
        /// <remarks/>
        UInt64,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Guid,
        
        /// <remarks/>
        TimeSpan,
        
        /// <remarks/>
        ByteArray,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30128.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devexpress.com/")]
    public partial class QuerySubQueryContainer : CriteriaOperator {
        
        private BaseStatement nodeField;
        
        private CriteriaOperator aggregatePropertyField;
        
        private Aggregate aggregateTypeField;
        
        /// <remarks/>
        public BaseStatement Node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
        
        /// <remarks/>
        public CriteriaOperator AggregateProperty {
            get {
                return this.aggregatePropertyField;
            }
            set {
                this.aggregatePropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Aggregate AggregateType {
            get {
                return this.aggregateTypeField;
            }
            set {
                this.aggregateTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30128.1")]
    public delegate void GetDataViewCompletedEventHandler(object sender, GetDataViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30128.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591